

services:
  back:
    container_name: fb-back
    build: ./back
    ports:
      - 8000:8000

  front:
    container_name: fb-front
    build: ./front
      
    ports:
      - 5000:4200
    depends_on:
      - back

  
